import { Router, type IRouter } from "express";
import healthRouter from "./health";
import organizationsRouter from "./organizations";
import fleetRouter from "./fleet";
import agentsRouter from "./agents";
import agentKeysRouter from "./agent-keys";
import areasRouter from "./areas";
import verdictActionsRouter from "./verdict-actions";
import discoveryRouter from "./discovery";
import connectorsRouter from "./connectors";
import catalogRouter from "./catalog";
import telemetryRouter from "./telemetry";
import mixedTeamsRouter from "./mixed-teams";
import performanceRouter from "./performance";
import evidenceRouter from "./evidence";
import journeysRouter from "./journeys";
import journeyRecommendationsRouter from "./journey-recommendations";
import continuousActivityRouter from "./continuous-activity";
import executiveReportsRouter from "./executive-reports";
import professionalPlansRouter from "./professional-plans";
import accessControlRouter from "./access-control";
import realtimeGovernanceRouter from "./realtime-governance";

const router: IRouter = Router();

router.use(healthRouter);
router.use(organizationsRouter);
router.use(fleetRouter);
router.use(agentsRouter);
router.use(agentKeysRouter);
router.use(areasRouter);
router.use(verdictActionsRouter);
router.use(discoveryRouter);
router.use(connectorsRouter);
router.use(catalogRouter);
router.use(telemetryRouter);
router.use(mixedTeamsRouter);
router.use(performanceRouter);
router.use(evidenceRouter);
router.use(journeysRouter);
router.use(journeyRecommendationsRouter);
router.use(continuousActivityRouter);
router.use(executiveReportsRouter);
router.use(professionalPlansRouter);
router.use(accessControlRouter);
router.use(realtimeGovernanceRouter);

export default router;
